# Generated by Django 2.0.7 on 2018-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('Number', models.IntegerField(choices=[(1, 2744), (2, 2704), (3, 2912), (4, 2798), (5, 982), (6, 1150)])),
                ('Prefix', models.BooleanField()),
                ('Suffix', models.IntegerField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')])),
                ('NumberOfFins', models.IntegerField(verbose_name=32)),
            ],
        ),
    ]
