# Generated by Django 2.0.7 on 2018-08-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.FloatField(null=True)),
                ('Thickness', models.FloatField(null=True)),
                ('Height', models.FloatField(null=True)),
                ('FinType', models.CharField(max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(choices=[(1, 2744), (2, 2704), (3, 2912), (4, 2798), (5, 982), (6, 1150)])),
                ('Prefix', models.BooleanField(default=False)),
                ('Suffix', models.IntegerField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')])),
                ('NumberOfFins', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.FloatField(null=True)),
                ('Thickness', models.FloatField(null=True)),
                ('Height', models.FloatField(null=True)),
                ('Rug', models.CharField(max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
