# Generated by Django 2.0.7 on 2018-08-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='length',
            name='CUBE_UNIT',
            field=models.IntegerField(choices=[('Inches', 'Inches'), ('Metric', 'Metric')], default=1),
        ),
    ]
