# Generated by Django 2.0.7 on 2018-08-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20180811_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angle',
            name='ANGLE_UNIT',
            field=models.CharField(choices=[('Degree', 'Degree'), ('Radian', 'Radian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='finshield',
            name='Prefix',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='length',
            name='CUBE_UNIT',
            field=models.CharField(choices=[('Inches', 'Inches'), ('Metric', 'Metric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='POS_UNIT',
            field=models.CharField(choices=[('Inches', 'Inches'), ('Metric', 'Metric')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weight',
            name='WEIGHT_UNIT',
            field=models.CharField(choices=[('lbs.', 'Pounds'), ('Kg', 'kilogram')], max_length=10),
        ),
    ]
