# Generated by Django 2.0.7 on 2018-08-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20180811_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='length',
            name='CUBE_UNIT',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='HoleRad',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='HoleThick',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='HoleWidth',
        ),
        migrations.AddField(
            model_name='length',
            name='REC_UNIT',
            field=models.CharField(choices=[('Inches', '"'), ('Metric(mm)', 'mm')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifold',
            name='HoleR',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifold',
            name='HoleRUnit',
            field=models.CharField(choices=[('Inches', '"'), ('Metric(mm)', 'mm')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifold',
            name='RUG_INFO',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Product.RUG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='angle',
            name='Angle',
            field=models.FloatField(blank=True, default=0, help_text='Degree'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='length',
            name='Broad',
            field=models.FloatField(blank=True, help_text='Width'),
        ),
        migrations.AlterField(
            model_name='length',
            name='Length',
            field=models.FloatField(blank=True, help_text='Size'),
        ),
        migrations.AlterField(
            model_name='length',
            name='Thickness',
            field=models.FloatField(blank=True, help_text='Depth'),
        ),
        migrations.AlterField(
            model_name='position',
            name='FROMLEFT',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='FROMRIGHT',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='FROMTOP',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='POS_UNIT',
            field=models.CharField(choices=[('Inches', '"'), ('Metric(mm)', 'mm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weight',
            name='WEIGHT_UNIT',
            field=models.CharField(choices=[('lbs.', 'lbs.'), ('Kilogram', 'kilogram')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weight',
            name='Weight',
            field=models.FloatField(blank=True),
        ),
    ]
