# Generated by Django 2.0.7 on 2018-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20180811_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifold',
            name='FluteDep',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifold',
            name='FluteWide',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='angle',
            name='ANGLE_UNIT',
            field=models.CharField(choices=[('Degree', '°'), ('Radian', '(rad)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weight',
            name='WEIGHT_UNIT',
            field=models.CharField(choices=[('Pounds', 'lbs.'), ('Kilogram', 'kg')], max_length=10),
        ),
    ]
