# Generated by Django 2.0.7 on 2018-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20180811_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='FROMLEFT',
            new_name='LEFT',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='FROMRIGHT',
            new_name='RIGHT',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='FROMTOP',
            new_name='TOP',
        ),
        migrations.RemoveField(
            model_name='fin',
            name='FINAngle',
        ),
        migrations.AddField(
            model_name='fin',
            name='FINAngle',
            field=models.ManyToManyField(blank=True, to='Product.Angle'),
        ),
        migrations.RemoveField(
            model_name='fin',
            name='FINSize',
        ),
        migrations.AddField(
            model_name='fin',
            name='FINSize',
            field=models.ManyToManyField(blank=True, to='Product.Length'),
        ),
        migrations.RemoveField(
            model_name='finshield',
            name='Manifold',
        ),
        migrations.AddField(
            model_name='finshield',
            name='Manifold',
            field=models.ManyToManyField(blank=True, to='Product.MANIFOLD'),
        ),
        migrations.RemoveField(
            model_name='finshield',
            name='Rug',
        ),
        migrations.AddField(
            model_name='finshield',
            name='Rug',
            field=models.ManyToManyField(blank=True, to='Product.RUG'),
        ),
        migrations.RemoveField(
            model_name='finshield',
            name='Weight',
        ),
        migrations.AddField(
            model_name='finshield',
            name='Weight',
            field=models.ManyToManyField(blank=True, to='Product.Weight'),
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='DIMENSION',
        ),
        migrations.AddField(
            model_name='manifold',
            name='DIMENSION',
            field=models.ManyToManyField(blank=True, to='Product.Length'),
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='HolePos',
        ),
        migrations.AddField(
            model_name='manifold',
            name='HolePos',
            field=models.ManyToManyField(blank=True, to='Product.Position'),
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='RUG_INFO',
        ),
        migrations.AddField(
            model_name='manifold',
            name='RUG_INFO',
            field=models.ManyToManyField(blank=True, to='Product.RUG'),
        ),
        migrations.RemoveField(
            model_name='rug',
            name='RUGPos',
        ),
        migrations.AddField(
            model_name='rug',
            name='RUGPos',
            field=models.ManyToManyField(blank=True, to='Product.Position'),
        ),
        migrations.RemoveField(
            model_name='rug',
            name='RUGSize',
        ),
        migrations.AddField(
            model_name='rug',
            name='RUGSize',
            field=models.ManyToManyField(blank=True, to='Product.Length'),
        ),
    ]
