# Generated by Django 2.0.7 on 2018-07-23 04:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderEmail', models.EmailField(max_length=254)),
                ('OrderedCompany', models.CharField(max_length=50)),
                ('ThePaper', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='Papers')),
                ('DeliveredDate', models.DateField()),
                ('ConfirmedDate', models.DateField()),
                ('LastUpload', models.DateField()),
                ('isStored', models.BooleanField(default=False)),
            ],
        ),
    ]
