# Generated by Django 2.0.7 on 2018-08-09 13:16

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderEmail', models.EmailField(max_length=254)),
                ('OrderedCompany', models.CharField(max_length=50)),
                ('ThePaper', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='Storage/Orders')),
                ('DeliveredDate', models.DateField(default=None, null=True)),
                ('LastQueryTime', models.DateField(default=None, null=True)),
                ('ConfirmedDate', models.DateField(default=None, null=True)),
                ('UploadDate', models.DateField(default=None, null=True)),
                ('DueDate', models.DateField(null=True)),
                ('isStored', models.BooleanField(default=False)),
                ('Goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
            ],
        ),
    ]
