# Generated by Django 2.0.7 on 2018-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveredDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='LastQueryTime',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='UploadDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
