# Generated by Django 2.0.7 on 2018-07-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Papers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Confirmed_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='DeliveredDate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='OrderCompany',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ReceiverEmail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ThePaper',
        ),
    ]
